# Generated by Django 5.0.6 on 2024-06-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
