# Generated by Django 5.0.6 on 2024-06-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_subscription_options_payment_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='сумма оплаты'),
        ),
    ]
