# Generated by Django 5.0.6 on 2024-06-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата обновления'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата обновления'),
        ),
    ]
